version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run generate
  post_build:
    commands:
       - aws s3 cp --recursive ./dist s3://intelrxinventory/
       - aws cloudfront create-invalidation --distribution-id EXBF0AA3YUYNR --path /\*
