name: Deploy Frontend - Dev.

on:

  push:

    branches: ["main"]



  workflow_dispatch:

jobs:

  build:

    name: Build

    runs-on: ubuntu-latest



    steps:

      - uses: actions/checkout@v3





      - name: SSH and Git Pull

        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.VPS_HOST }}

          username: ${{ secrets.VPS_USERNAME }}

          key: ${{ secrets.VPS_KEY }}

          port: ${{ secrets.VPS_PORT }}

          script: |

            echo "Successfully ssh into Staging Server"

            echo "Setting up Git credentials for the pull"

            git config --global user.email "actions@github.com"

            git config --global user.name "GitHub Actions"

            git config --global credential.helper store

            echo "machine github.com login ${{ secrets.GIT_TOKEN }} password x-oauth-basic" > ~/.netrc

            echo "Pulling the updated commit into the server"

            cd ~/Frontend-Pharmacist

            git checkout main

            git pull origin main



      - name: SSH into server and build Docker image.

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.VPS_HOST }}

          username: ${{ secrets.VPS_USERNAME }}

          key: ${{ secrets.VPS_KEY }}

          port: ${{ secrets.VPS_PORT }}

          script: |

            cd ~/Frontend-Pharmacist

            sudo docker stop pharmacy || true

            sudo docker rm -f pharmacy || true

            sudo docker build -t pharmacy .
            sudo docker run -d --name pharmacy -p 3000:80 pharmacy
            sudo docker system prune -f
